# -*- coding: utf-8 -*-
"""Python_Refresher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4XtTEkNaVb2T2mSrFqhOjpmmRQr90ah
"""

#question 1:
import math

def daysToSeconds():
  days = int(input("Enter the number of days"))
  seconds = days * 24 * 60 * 60
  print(seconds)

  #Example
  if __name__ == "__main__":
    daysToSeconds()

#question 2:
import math

def sphereVolume():
    r = float(input("Enter sphere radius: "))
    volume = (4.0/3.0) * math.pi * (r ** 3)
    print(f"Volume = {volume:.6f}")

# Example usage
if __name__ == "__main__":
    sphereVolume()

#question 3:
def perimeter():

    s = float(input("Enter the length of the square: "))
    area = s * s
    perimeter = 4 * s
    print(f"Area: {area:.6f}")
    print(f"Perimeter: {perimeter:.6f}")

# Example usage
if __name__ == "__main__":
    perimeter()

#question 4:

def charCase():

    ch = input("Enter a single character: ").strip()

    if len(ch) != 1 or not ch.isalpha():

        print("Please enter exactly one alphabetic character.")

        return

    if ch.isupper():

        print("uppercase")

    else:

        print("lowercase")



# Example usage

if __name__ == "__main__":

    charCase()

#question 5:

import math
from typing import List

def absoluteDistinctCount(A: List[int]) -> int:
    if not A:
        return 0  # though the problem states non-empty

    count = 1
    prev_abs = abs(A[0])

    for x in A[1:]:
        cur_abs = abs(x)
        if cur_abs != prev_abs:
            count += 1
            prev_abs = cur_abs

    return count

# Example usage
if __name__ == "__main__":
    A1 = [-5, -3, -1, 0, 3, 4, 6]
    print("absoluteDistinctCount:", absolute_distinct_count(A1))  # 5

    A2 = [-7, -4, -2, 0, 1, 3, 3, 4]
    print("absoluteDistinctCount:", absolute_distinct_count(A2))  # 6

#question 6:

def valAndAvg() -> float:
    values = []
    print("Enter 5 values:")
    while len(values) < 5:
        try:
            v = float(input(f"Value {len(values) + 1}: "))
            values.append(v)
        except ValueError:
            print("Please enter a valid number.")
    avg = sum(values) / len(values)
    print("The entered values:", values)
    print(f"Average = {avg:.6f}")
    return avg

# Example usage
if __name__ == "__main__":
    valAndAvg()